- name: Installing the maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Import the  app prereq files
  ansible.builtin.import_tasks: app-prereq.yml

- name: Installing the Application Dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: Import the schema files
  ansible.builtin.import_tasks: mysql-schema.yml
  when: schema is defined

- name: Import the systemd files
  ansible.builtin.import_tasks: systemd.yml