- name: Setup hostname
  ansible.builtin.shell: set-hostname {{ component }}

- name: Creating a roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Deleting content in app folder
  ansible.builtin.file:
    path: /app
    state: absent

- name: Creating a Application folder
  ansible.builtin.file:
    path: /app
    state: directory

- name: Downloading and unzipping the application code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes
