- name: Copying mongodb repo files
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing the Mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Download DocumentDB pem file
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem



- name: Loading the mongodb schema
  ansible.builtin.shell: mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', 'docdb.{{env}}.endpoint', region='us-east-1') }}:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username docdbadmin --password roboshop1234 </app/schema/{{component}}.js

